title: "My Lapis Blog"
baseurl: "http://localhost:3000"
description: "A beautiful blog built with Lapis static site generator"
author: "Blog Author"

# Build settings
output_dir: "public"
permalink: "/:year/:month/:day/:title/"

# Server settings
port: 3000
host: "localhost"

# Markdown settings
markdown:
  syntax_highlighting: true
  toc: true
  smart_quotes: true
  footnotes: true
  tables: true