title: "Lapis Example Site"
baseurl: "http://localhost:3000"
description: "Showcasing the power of Crystal-based static site generation with modern features"
author: "Lapis Team"
theme: "default"

# Blog-specific settings
posts_per_page: 10
excerpt_length: 200
show_reading_time: true

# Social links
social:
  twitter: "lapis_ssg"
  github: "lapis-lang/lapis"
  email: "hello@lapis-example.com"

# SEO settings
google_analytics: ""
facebook_app_id: ""

# Build settings
output_dir: "public"
permalink: "/:year/:month/:day/:title/"

# Server settings
port: 3000
host: "localhost"

# Advanced features
markdown:
  syntax_highlighting: true
  toc: true
  smart_quotes: true
  footnotes: true