name: CI

on:
  push:
    branches: [ main, v0.3.0 ]
  pull_request:
    branches: [ main, v0.3.0 ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Crystal
      uses: crystal-lang/install-crystal@v1
      with:
        crystal: "1.10.1"

    - name: Install dependencies
      run: shards install

    - name: Run tests
      run: crystal spec

    - name: Build binary
      run: crystal build src/lapis.cr --release -o bin/lapis

    - name: Test example site
      run: |
        cd exampleSite
        ../bin/lapis build
        test -f public/index.html
